services:
  laravel-db:
    image: postgres:17.1
    container_name: laravel-db
    ports:
      - 5440:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: laravel
    networks:
      - laravel-network
    volumes:
      - laravel-db:/var/lib/postgresql/data

  laravel:
    build:
      args:
        USER_ID: 1000
        GROUP_ID: 1000
        USER_NAME: admin
        GROUP_NAME: admin 
      context: .
      dockerfile: ./Dockerfile
    image: "laravel"
    container_name: laravel
    working_dir: /var/www/html
    networks:
      - laravel-network
    volumes:
      - ./laravel:/var/www/html
    depends_on:
      - laravel-db

  laravel-server:
    image: nginx:alpine
    container_name: laravel-server
    ports:
      - 9000:9000
    networks:
      - laravel-network
    volumes:
      - ./config/nginx/app.conf:/etc/nginx/conf.d/default.conf
      - ./laravel:/var/www/html
    depends_on:
      - laravel

networks:
  laravel-network:
    driver: bridge
    name: laravel-network

volumes:
  laravel-db:
    name: laravel-db